import random

FONT_COLOUR = (255, 255, 255)
WIDTH = 800
HEIGHT = 800
CENTRE_X = WIDTH / 2
CENTER_Y = HEIGHT / 2
CENTRE = (CENTRE_X, CENTER_Y)
FINAL_LEVEL = 6
START_SPEED = 10
COLOURS = ["green", "blue"]
